name             'breakfix'
maintainer       'Giovanni Del Valle'
maintainer_email 'gdelvalle@gmail.com'
license          'All rights reserved'
description      'Installs/Configures breakfix'
long_description 'Installs/Configures breakfix'
version          '0.1.0'
